title: a cup of tea
email: cole@staymellow.ai
description: >-
  my (not so) well thought out blog
baseurl: ""
url: "https://colesmcintosh.github.io"
github_username: colesmcintosh
twitter_username: colesmcintosh

theme: minima
plugins:
  - jekyll-feed
